services:
  rsspub:
    ports:
      - "3000:3000"
    image: harshit181/rsspub:latest
    volumes:
      - ${EPUBS_HOST_DIR:-./db}:/app/db
    environment:
      - RUST_LOG=info,html5ever=error
      - RPUB_USERNAME=${RPUB_USERNAME}
      - RPUB_PASSWORD=${RPUB_PASSWORD}
    restart: unless-stopped
